# Generated by Django 4.2.3 on 2024-02-08 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProducto', models.CharField(default='', max_length=120, verbose_name='Producto')),
                ('cAgrupacion', models.CharField(choices=[('Caja', 'Cj'), ('Paquete', 'Pqte'), ('Unidad', 'Und')], default='Unidad', max_length=120, verbose_name='Agrupación')),
                ('nPrecioDia', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Día')),
                ('nPrecioNoche', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio Noche')),
                ('nConversion', models.IntegerField(default=1, verbose_name='Conversión')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nCantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('nPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('dFecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Venta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMostrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nCantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('dFechaMod', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_mostrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nCantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('dFechaMod', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Almacen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nMontoApertura', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Monto Apertura')),
                ('dFechaApertura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Apertura')),
                ('cComentarioApertura', models.CharField(default='', max_length=120, verbose_name='Comentario Apertura')),
                ('nMontoCierre', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Monto Cierre')),
                ('dFechaCierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('cComentarioCierre', models.CharField(default='', max_length=120, verbose_name='Comentario Cierre')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
