# Generated by Django 4.2.3 on 2024-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_stockmostrador_ccantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalmacen',
            name='cCantidad',
            field=models.CharField(default='', max_length=120, verbose_name='cCantidad'),
        ),
    ]
