# Generated by Django 4.2.3 on 2024-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_stockalmacen_ccantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalmacen',
            name='cCantidad',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cCantidad'),
        ),
        migrations.AlterField(
            model_name='stockmostrador',
            name='cCantidad',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cCantidad'),
        ),
    ]
