# Generated by Django 4.2.3 on 2024-02-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0005_alter_stockalmacen_ccantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nCantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('nPrecio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('dFecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_Entrada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stockalmacen',
            name='cCantidad',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cantidad'),
        ),
        migrations.DeleteModel(
            name='StockMostrador',
        ),
    ]
