# Generated by Django 4.2.3 on 2024-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_entrada_alter_stockalmacen_ccantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='cTurno',
            field=models.CharField(choices=[('Turno Dia', 'Turno Dia'), ('Turno Noche', 'Turno Noche')], default='Turno Dia', max_length=120, verbose_name='Turno'),
        ),
    ]
