# Generated by Django 4.2.3 on 2024-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_venta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nSubTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sub Total'),
        ),
    ]
